### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by ariscn** [nylas/make-deb#7]
It would be great if make-deb could bump `debian/changelog` from the latest git commit, instead of only on first-run.

**Comment by systemizer** [comment]
Thanks for the feedback! To make sure I understand your request, you would like to run make-deb multiple times and have it update the latest git commit in the changelog after each run?

If you run make-deb multiple times right now, it will just steamroll itself and add the commit at HEAD to the changelog. It was originally only meant for setting up the debian configuration, so this fit its use case. 

If we want make-deb to append data to currently existing debian configurations, we're going to need to write a debian configuration parser (ouch!). This it out of the scope of make-deb, but could otherwise be a useful tool. And if someone builds that tool, I'll be happy to extend make-deb to use it.

It looks like python-debian might do this, but I'm afraid of using it due to the lack of documentation and maintenance. 

Let me know if that makes sense. Feel free to reopen if I'm misunderstanding. Thanks again!

**Comment by ariscn** [comment]
Thanks for the thorough reply! I'm a Python guy and haven't done much work with Debian packaging. I've been using make-deb and dh-virtualenv for a few weeks, and overall, they're great tools. But maintaining the Debian changelog file is a PITA - I need to bump it to generate a new versioned file, and that needs to be done manually every time. This is error-prone and feels like duplicating work - how did you solve this for your own projects?

**Comment by spang** [comment]
We don't bump the Debian version numbers when generating new builds—we put the gitsha of the build in the package's filename, and all of our deploy tooling uses that scheme to handle versions.

If you need to bump the Debian version, I recommend the `dch` script included in the `devscripts` package: https://packages.debian.org/sid/devscripts
On Sep 2 2015, at 6:27 pm, ariscn notifications@github.com wrote:

Thanks for the thorough reply! I'm a Python guy and haven't done much work with Debian packaging. I've been using make-deb and dh-virtualenv for a few weeks, and overall, they're great tools. But maintaining the Debian changelog file is a PITA - I need to bump it to generate a new versioned file, and that needs to be done manually every time. This is error-prone and feels like duplicating work - how did you solve this for your own projects?

**Comment by ariscn** [comment]
How do you get the git SHA into the filename?

**Comment by systemizer** [comment]
This is done separately (not in make-deb) during our own build process. make-deb is good at simply packaging python code into a debian package. We don't rely on it as much for other features of Debian packages (i.e. version numbers) to ship our code. Putting the git SHA in the changelog is just metadata for humans to understand what is in the package.
